#!/bin/bash
python3 -c 'w,b,s=map("".join,[["e","w","a","t","r"],["b","e","s","t","c","h","o","l"],["t","i",".","r"]]);a=sum(w.index(c)*5**i for i,c in enumerate(reversed(__import__("os").environ["WATER"])));d=sum(s.index(c)*4**i for i,c in enumerate(reversed(__import__("os").environ["STIR"])));n=a+d;r="";exec("while n:r=b[n%8]+r;n//=8");print(r)'
