#!/usr/bin/env bash
# Display all running processes with start time including seconds

ps -eo user,pid,pcpu,pmem,vsz,rss,tty,stat,lstart,time,command --forest | \
awk 'NR==1 {print "USER       STARTED COMMAND"; next} {printf "%-10s %8s %s\n", $1, $6":"$7":"$8, $12}'

