#!/usr/bin/env bash
# Displays all currently running processes with user info,
# no matter the TTY, in a hierarchical tree format.

ps -eo user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,command --forest

